import "./globals.css";
import { Poppins } from "next/font/google";

import Nav from "@/components/Nav";

const globalFont = Poppins({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={globalFont.className}>
        <Nav />
        <div className="container mx-auto p-5">{children}</div>
      </body>
    </html>
  );
}
